apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
  namespace: folder4study
  labels:
    app: grafana
    version: latest
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      name: grafana
      namespace: folder4study
      labels:
        app: grafana
        version: latest
    spec:
      securityContext:
        fsGroup: 472
        supplementalGroups:
          - 0
      containers:
        - name: grafana
          image: grafana/grafana:latest
          imagePullPolicy: IfNotPresent
          ports:
            - name: port
              containerPort: 3000
              protocol: TCP
          volumeMounts:
            - mountPath: /var/lib/grafana
              name: grafana
          securityContext:
            runAsUser: 0
            runAsGroup: 0
      volumes:
        - name: grafana
          persistentVolumeClaim:
            claimName: grafana