kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: grafana
  namespace: folder4study
  labels:
    app: grafana
    version: latest
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi