apiVersion: v1
kind: Service
metadata:
  name: grafana
  namespace: folder4study
  labels:
    app: grafana
    version: latest
spec:
  type: LoadBalancer
  selector:
    app: grafana
  ports:
    - name: port
      port: 3000
      targetPort: port
